var searchData=
[
  ['mean_5fabsolute_5ferror_0',['mean_absolute_error',['../group__Metrics.html#ga4ff2225cb37f1bb73f4d43a265dac44b',1,'VSTAT_NAMESPACE::metrics::mean_absolute_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2) noexcept -&gt; double'],['../group__Metrics.html#gaa3e4f47e3af64f17a97ed9480d909131',1,'VSTAT_NAMESPACE::metrics::mean_absolute_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2, K first3) noexcept -&gt; double']]],
  ['mean_5fabsolute_5fpercentage_5ferror_1',['mean_absolute_percentage_error',['../group__Metrics.html#ga8f24fc8e1cfd7b59d5793b1acd7b8f42',1,'VSTAT_NAMESPACE::metrics::mean_absolute_percentage_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2) noexcept -&gt; double'],['../group__Metrics.html#ga976987101422e09577b8835d7b23a83e',1,'VSTAT_NAMESPACE::metrics::mean_absolute_percentage_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2, K first3) noexcept -&gt; double']]],
  ['mean_5fsquared_5ferror_2',['mean_squared_error',['../group__Metrics.html#gaf258ad1043ee576fec45c3ad5be822df',1,'VSTAT_NAMESPACE::metrics::mean_squared_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2) noexcept -&gt; double'],['../group__Metrics.html#gaf5ae47f5b84b264f7fcf67d794d281ab',1,'VSTAT_NAMESPACE::metrics::mean_squared_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2, K first3) noexcept -&gt; double']]],
  ['mean_5fsquared_5flog_5ferror_3',['mean_squared_log_error',['../group__Metrics.html#gaec59c3bec2b06f9f4a975ece9cd61172',1,'VSTAT_NAMESPACE::metrics::mean_squared_log_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2) noexcept -&gt; double'],['../group__Metrics.html#ga7bf9e9d88861bc7af4431ebfe8e4ce81',1,'VSTAT_NAMESPACE::metrics::mean_squared_log_error(I first1, std::sentinel_for&lt; I &gt; auto last1, J first2, K first3) noexcept -&gt; double']]],
  ['methodology_4',['methodology',['../index.html#autotoc_md6',1,'Methodology'],['../md_index.html#autotoc_md10',1,'Methodology']]],
  ['metrics_5',['Regression metrics',['../group__Metrics.html',1,'']]]
];
